apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
spec:
  capacity:
    storage: 1.8Ti 
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/raid/nextcloud-data  # Path to the nextcloud-data directory on your external drive
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual