apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1.8Ti  # Match the size of your external drive
  storageClassName: manual